In [ ]:
import numpy as np

## Basics

In [ ]:
a = np.array([1, 2, 3, 4, 5], dtype='float32')
print(a.ndim)
print(a.shape)
a

1
(5,)


array([1., 2., 3., 4., 5.], dtype=float32)

In [ ]:
b = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10] ])
print(b.ndim)
print(b.shape)
b

2
(2, 5)


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

## Retrieving a specific element

In [ ]:
b[:, 2]  # getting all elements in the third column

array([3, 8])

In [ ]:
b[1, :] # getting all elements in the second row

array([ 6,  7,  8,  9, 10])

In [ ]:
b_copy = np.copy(b)
b_copy[0, 0] = 10
b_copy

array([[10,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

## Replacing Elements

In [ ]:
c = np.array([[1, 2], [4, 5]])
print(c)

c[1, :] = [8, 8]
c

[[1 2]
 [4 5]]


array([[1, 2],
       [8, 8]])

## Different Types of arrays

In [ ]:
# Zeros
z = np.zeros((2, 3), dtype='int32')
z

array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
# Ones
ones_example = np.ones((4, 1, 2), dtype='float32')
ones_example

array([[[1., 1.]],

       [[1., 1.]],

       [[1., 1.]],

       [[1., 1.]]], dtype=float32)

In [ ]:
# Full
full_example = np.full((3, 3), 11)
full_example

array([[11, 11, 11],
       [11, 11, 11],
       [11, 11, 11]])

In [ ]:
# Random Numbers
random_example = np.random.randint(-10, 20, size=(5, 5))
random_example

array([[ -3,   9,   2,  15,  -6],
       [  9,   0, -10,  15,  13],
       [ -5,   8,   7,   0,  16],
       [ -2,  16,  -5,   7,   8],
       [  4,  -3,  18,  -1,  -2]])

In [ ]:
# Random Numbers
random_example2 = np.arange(-10, 10, step=3)
random_example2

array([-10,  -7,  -4,  -1,   2,   5,   8])

## Linear Algebra

In [ ]:
mat_a = np.ones((2, 2))
mat_b = np.full((2, 2), 3)

print(mat_a)
print(mat_b)

mult = np.matmul(mat_a, mat_b)
print('matrix multiplication: ', mult)

det = np.linalg.det(mult)
print('determinant of the multiplication: ', det)

[[1. 1.]
 [1. 1.]]
[[3 3]
 [3 3]]
matrix multiplication:  [[6. 6.]
 [6. 6.]]
determinant of the multiplication:  0.0


In [ ]:
## Another Example
iden = np.identity(3)
print(iden)
np.linalg.det(iden)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


1.0

## Statistics

In [ ]:
stat_example = np.random.randint(0, 100, size=(3, 3))
stat_example

array([[10, 91,  7],
       [50,  7, 16],
       [70, 98, 78]])

In [ ]:
print('min: ', np.min(stat_example))
print('max: ', np.max(stat_example))
print('average: ', np.mean(stat_example))
print('sum of all rows and columns: ', np.sum(stat_example))
print('standard deviation: ', np.std(stat_example))

min:  7
max:  98
average:  47.44444444444444
sum of all rows and columns:  427
standard deviation:  35.845691236840636


## Reorganizing

In [ ]:
before_reshape = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(before_reshape)

print("---------------------------")

after_reshape1 = np.reshape(before_reshape, (2, 4))
print('2*4 matrix: ', after_reshape1)

print("---------------------------")

after_reshape2 = np.reshape(before_reshape, (4, 2))
print('4*2 matrix: ', after_reshape2)

print("---------------------------")

after_reshape3 = np.reshape(before_reshape, (8, 1))
print(after_reshape3)

[1 2 3 4 5 6 7 8]
---------------------------
2*4 matrix:  [[1 2 3 4]
 [5 6 7 8]]
---------------------------
4*2 matrix:  [[1 2]
 [3 4]
 [5 6]
 [7 8]]
---------------------------
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


## Vertically & Horizontaly Stacking Vectors

In [ ]:
first = np.array([1, 2, 3, 4, 5])
second = np.array([6, 7, 8, 9, 10])
third = np.array([11, 12, 13, 14, 15])

v_result = np.vstack([first, second, third, second])
v_result

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [ 6,  7,  8,  9, 10]])

In [ ]:
first_t = np.transpose(first)
second_t = np.transpose(second)
third_t = np.transpose(third)

h_result = np.hstack([first_t, second_t, third_t])
h_result

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

## Boolean

In [ ]:
random_example = np.random.randint(-100, 100, size=(4, 4))
random_example

array([[  38,   82,   -2,  -18],
       [  79,   73,   19,  -38],
       [ -43,  -78, -100,   18],
       [  95,   68,   62,  -57]])

In [ ]:
random_example > 0

array([[ True,  True, False, False],
       [ True,  True,  True, False],
       [False, False, False,  True],
       [ True,  True,  True, False]])

In [ ]:
!pip install jovian --upgrade --quiet

In [ ]:
import jovian

<IPython.core.display.Javascript object>

In [ ]:
jovian.commit(project='01-numpy-tutorial')

<IPython.core.display.Javascript object>

[jovian] Please enter your API key ( from https://jovian.ai/ ):
API KEY: ········
[jovian] Creating a new project "amirhallaji/01-numpy-tutorial"
[jovian] Committed successfully! https://jovian.ai/amirhallaji/01-numpy-tutorial


'https://jovian.ai/amirhallaji/01-numpy-tutorial'