In [1]:
import torch

In [5]:
t1 = torch.tensor(5)
t1

tensor(5)

In [6]:
t1.dtype

torch.int64

In [7]:
t2 = torch.tensor([1, 2, 3])
print(t2)

tensor([1, 2, 3])


In [15]:
t3 = torch.tensor([[1, 2, 3],[4, 5, 6], [7, 8, 9]])
t3

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [9]:
t1.shape

torch.Size([])

In [10]:
t2.shape

torch.Size([3])

In [13]:
t3.shape

torch.Size([3, 3])

## y = w * x + b  AutoGrad

In [18]:
x = torch.tensor(5.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(6., requires_grad=True)
y = w * x + b

In [19]:
y.backward()

In [21]:
print('dy/dx: ', x.grad)
print('dy/dw: ', w.grad)
print('dy/db: ', b.grad)

dy/dx:  None
dy/dw:  tensor(5.)
dy/db:  tensor(1.)


## Simple Methods

In [22]:
t4 = torch.full((3, 2), 60)
t4

tensor([[60, 60],
        [60, 60],
        [60, 60]])

In [23]:
t5 = torch.full((3, 2), 80)
t5

tensor([[80, 80],
        [80, 80],
        [80, 80]])

In [24]:
t6 = torch.cat((t4, t5))
t6

tensor([[60, 60],
        [60, 60],
        [60, 60],
        [80, 80],
        [80, 80],
        [80, 80]])

In [25]:
import numpy as np

In [28]:
x = np.array([1., 2, 3])
x

array([1., 2., 3.])

In [29]:
t7 = torch.from_numpy(x)
t7

tensor([1., 2., 3.], dtype=torch.float64)

In [30]:
y = t7.numpy()
y

array([1., 2., 3.])